name: 'Terraform Pipeline'
description: 'Terraform Pipeline'
inputs:
  pipeline-action:  # id of input
    description: 'Action for the Pipeline'
    required: true
    default: 'CI'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: |
            sudo apt install curl
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            sudo apt update
            sudo apt-get install terraform
      shell: bash

    
    - run: echo Hello CI
      shell: bash
      if: ${{ inputs.pipeline-action == 'CI' }}
    
    - name: tfsec
      uses: tfsec/tfsec-pr-commenter-action@v0.1.4
      if: ${{ inputs.pipeline-action == 'PR' }}

    - name: tfsec
      uses: tfsec/tfsec-sarif-action@v0.1.4
      with:
        sarif_file: tfsec.sarif 
      if: ${{ inputs.pipeline-action == 'PR' }}

    - name: Terraform Initalization
      run: terraform init
      shell: bash
      if: ${{ inputs.pipeline-action == 'CI' }}

    - name: Terraform Plan
      run: terraform plan
      shell: bash
      if: ${{ inputs.pipeline-action == 'CI' }}

    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - run: ls -ltr
      shell: bash
