name: 'Terraform Pipeline'
description: 'Terraform Pipeline'
inputs:
  pipeline-action:  # id of input
    description: 'Action for the Pipeline'
    required: true
    default: 'CI'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: |
            sudo apt install curl
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            sudo apt update
            sudo apt-get install terraform
      shell: bash
    - run: echo "$GOOGLE_APPLICATION_CREDENTIALS_DATA" > gcloud_app.json
      shell: bash 

    - name: Terraform Initalization
      run: pwd && ls -ltr && terraform init
      shell: bash

    - name: Terraform Plan
      run: terraform plan
      shell: bash

    - name: Terraform Apply
      run: terraform apply -auto-approve
      shell: bash

    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - run: ls -ltr
      shell: bash
