name: 'Terraform Plan'
description: 'Terraform Plan'
inputs:
  var-file-path:
    description: 'Terraform variable file path'
    required: true
  secret:
    description: 'Terraform secret'
    required: true
runs:
  using: "composite"
  steps:
    - name: Terraform Plan
      shell: bash
      run: |
        echo "::group::Terraform workspace plan"
        terraform plan -no-color -out=terraform.plan #-var-file=${{ inputs.var-file-path }} 
        echo "::endgroup::"
